adding help and options to repo commands

diff --git a/.local/bin/repo b/.local/bin/repo
--- a/.local/bin/repo
+++ b/.local/bin/repo
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=0.0.1
+VERSION=1.0.0
 
 REPO_DIR=${REPO_DIR:-$HOME/repos}
 REPO_CONFIG=${REPO_CONFIG:-$HOME/.config/repo/config}
@@ -11,7 +11,7 @@ function main()
   FULL_COMMAND="$*"
 
   internal_commands="^(add|bootstrap|config|enter|foreach|help|list)$"
-  [[ -z "$*" ]] && help
+  [[ -z "$*" ]] && help 0
 
   if [[ "$1" =~ $internal_commands ]]; then
     REPO_COMMAND="$1"
@@ -19,36 +19,79 @@ function main()
 
     $REPO_COMMAND "$@"
   else
-    help 0
+    help 1
   fi
   die 0
 }
 
 function add()
 {
-  [ $# -eq 0 ] && echo "Failed: No category or url provided" && die 1
-  [ $# -eq 1 ] && echo "Failed: No name provided" && die 1
-  [ $# -eq 2 ] && echo "Failed: No url provided" && die 1
+  # Todo; add verbose output
+  local positional_args=()
+  local optspec=":hxvf"
+  while [ $# -gt 0 ]; do
+    unset OPTIND && unset OPTARG
+    while getopts $optspec OPTION ; do
+      case "$OPTION" in
+        h) help add 0          ;;
+        v) verbose true        ;;
+        x) exclude_config=true ;;
+        f) force_add=true      ;;
+        \?) echo "Invalid option $OPTION" help add 1 ;; 
+      esac
+    done
+    shift $((OPTIND-1)) ; positional_args+=("$1") ; shift
+  done
 
-  local category=$1
-  local name=$2
-  local url=$3
+  [ ${#positional_args[@]} -eq 0 ] && echo "Failed: No category or url provided" && die 1
+  [ ${#positional_args[@]} -eq 1 ] && echo "Failed: No name provided" && die 1
+  [ ${#positional_args[@]} -eq 2 ] && echo "Failed: No url provided" && die 1
+
+  local category=${positional_args[0]}
+  local name=${positional_args[1]}
+  local url=${positional_args[2]}
 
   [ ! -d $REPO_DIR ] && mkdir -p $REPO_DIR
 
   cd ${REPO_DIR}
   [[ -d $category/$name && $(ls -A $category/$name) ]] && {
-    echo "$category/$name already exists and is not an empty directory"
-    return
+    [[ -n $force_add ]] && {
+      echo "Force add (-f) was specified. Deleting old repo folder"
+      rm -rf $category/$name
+    } || {
+      echo "$category/$name already exists and is not an empty directory. Use -f to force readd it"
+      return
+    }
   }
 
-  git clone --recurse-submodules -j8 $url $category/$name && {
-    git config --file="${REPO_BOOTSTRAP}" $category.$name "$url"
+  echo git clone --recurse-submodules -j8 $url $category/$name && {
+    [ -z $exclude_config ] && git config --file="${REPO_BOOTSTRAP}" $category.$name "$url"
   }
 }
 
 function bootstrap()
 {
+  local positional_args=()
+  local optspec=":hvec"
+  while [ $# -gt 0 ]; do
+    unset OPTIND && unset OPTARG
+    while getopts $optspec OPTION ; do
+      case "$OPTION" in
+        h) help add 0          ;;
+        v) verbose true        ;;
+        e) edit true           ;;
+        \?) echo "Invalid option $OPTION" help bootstrap 1 ;; 
+      esac
+    done
+    shift $((OPTIND-1)) ; positional_args+=("$1") ; shift
+  done
+
+  [ -n $edit ] && {
+    [ ! -f $REPO_BOOTSTRAP ] && touch $REPO_BOOTSTRAP
+    $EDITOR $REPO_BOOTSTRAP
+    die 0
+  }
+
   [ ! -f $REPO_BOOTSTRAP ] && echo "Failed to find ${REPO_BOOTSTRAP}" && die 1
 
   [ ! -d $REPO_DIR ] && mkdir -p $REPO_DIR
@@ -135,26 +178,15 @@ function foreach()
 
 function help()
 {
-    cat << EOF
-Usage: repo <command> [options...]
+  [[ "$1" =~ $internal_commands ]] && cmd=help_$1 || cmd=help_overall
 
-Manage all projects and repositories under a root folder. List, switch, batch edit repositories
+  local number_regex='^-?[0-9]+$'
+  [[ "$1" =~ $number_regex ]] && return_code=$1
+  [[ "$2" =~ $number_regex ]] && return_code=$2
+  [[ -z "$return_code" ]] && return_code=0
 
-Commands:
-  repo add <category> <url> [name] - Add a repository url in a category
-  repo bootstrap [-f]              - Initialize a repo folder structure from a list file
-  repo config <name> <value>       - Configure a setting
-  repo enter name                  - Create a new shell in the root directory of a the repo
-  repo foreach [options] command   - Preform operation on all repos
-  repo help                        - Show this help message
-  repo list [-a]                   - List current repos visable by repo
-
-Files:
-  \$HOME/.config/repos/config - repo's config file
-  \$HOME/.config/repos/bootstrap - Default repo list file for \'bootstrap\'
-EOF
-
-  die 0
+  $cmd
+  die $return_code
 }
 
 function list()
@@ -220,6 +252,71 @@ function list()
   #   done
   #   echo ""
   # done
+}
+
+#
+# ─── HELP COMMANDS ──────────────────────────────────────────────────────────────
+#
+
+function help_overall()
+{
+  cat << EOF
+Usage: repo <command> [options...]
+
+Manage all projects and repositories under a root folder. List, switch, batch edit repositories
+
+Commands:
+  repo add <category> <url> [name] - Add a repository url in a category
+  repo bootstrap [-f]              - Initialize a repo folder structure from a list file
+  repo config <name> <value>       - Configure a setting
+  repo enter name                  - Create a new shell in the root directory of a the repo
+  repo foreach [options] command   - Preform operation on all repos
+  repo help                        - Show this help message
+  repo list [-a]                   - List current repos visable by repo
+
+Files:
+  \$HOME/.config/repos/config    - repo's config file
+  \$HOME/.config/repos/bootstrap - Default repo list file for \'bootstrap\'
+EOF
+}
+
+function help_add()
+{
+  cat << EOF
+Usage: repo add [options...] <category> <url> <name>
+
+Add a new repository into the \$REPO_DIR folder ($REPO_DIR).
+
+Options:
+  -h     Show this help message
+  -x     Do not add this entry into the bootstrap file
+  -f     Force add repository to location 
+EOF
+}
+
+function help_bootstrap()
+{
+  echo "bootstrap"
+}
+
+function help_config()
+{
+  echo "config"
+}
+
+function help_enter()
+{
+  echo "enter"
+}
+
+function help_foreach()
+{
+  echo "foreach"
+}
+
+function help_list()
+{
+  echo "list"
 }
 
 #
